// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAmL0_ZzmCYysjAoCL7-rqdBeI4JbUWSkY',
//     appId: '1:843655214318:web:524a0b6ee680f9a9386fff',
//     messagingSenderId: '843655214318',
//     projectId: 'neighborgood-e47ba',
//     authDomain: 'neighborgood-e47ba.firebaseapp.com',
//     storageBucket: 'neighborgood-e47ba.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDdVUlABAydyC2GNOFqhrNdLMeiGe7CrMo',
//     appId: '1:843655214318:android:f6fc8c24232cce58386fff',
//     messagingSenderId: '843655214318',
//     projectId: 'neighborgood-e47ba',
//     storageBucket: 'neighborgood-e47ba.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCu95sucKvPQKzNsORDhR05b_9NtpCycJs',
//     appId: '1:843655214318:ios:6bbe2e49a3f15f0f386fff',
//     messagingSenderId: '843655214318',
//     projectId: 'neighborgood-e47ba',
//     storageBucket: 'neighborgood-e47ba.appspot.com',
//     androidClientId: '843655214318-ebnvu298ambrbqnn1f39sb3hhmc9gi33.apps.googleusercontent.com',
//     iosClientId: '843655214318-a8iragcnl21susl4kqncoglsr39j0pb5.apps.googleusercontent.com',
//     iosBundleId: 'com.example.neighborgood',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAmL0_ZzmCYysjAoCL7-rqdBeI4JbUWSkY',
//     appId: '1:843655214318:web:28c010b0e0336231386fff',
//     messagingSenderId: '843655214318',
//     projectId: 'neighborgood-e47ba',
//     authDomain: 'neighborgood-e47ba.firebaseapp.com',
//     storageBucket: 'neighborgood-e47ba.appspot.com',
//   );
// }
